export const ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
  RIDER: "RIDER",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  PREPARING: "PREPARING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};
